// This file was autogenerated by calcdeps.py
goog.addDependency('../../../jsprettify/prettify.js', ['prettify.prettify', 'prettify.entities'], []);
goog.addDependency('../../../jsprettify/deps.js', [], []);
