// This file was autogenerated by calcdeps.py
goog.addDependency('../../../jsprettify/prettify.js', ['jsprettify.entities', 'jsprettify.prettifyHtml', 'jsprettify.prettifyStr', 'window.prettify'], ['goog.array', 'goog.dom']);
goog.addDependency('../../../jsprettify/bookmarklet.js', [], []);
goog.addDependency('../../../jsprettify/deps.js', [], []);
goog.addDependency('../../../jsprettify/alltests.js', [], []);
