// This file was autogenerated by calcdeps.py
goog.addDependency('../../../jsprettify/prettify.js', ['jsprettify.prettify', 'jsprettify.entities'], []);
goog.addDependency('../../../jsprettify/deps.js', [], []);
